[2016-09-30 07:10:04] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfC939.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:13:45] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckf8C77.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:23:03] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckf122E.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:23:42] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfA7BA.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:25:06] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfF133.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:25:06] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfF1E1.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:25:06] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfF27F.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:25:07] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfF32D.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:25:07] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfF3CC.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-09-30 16:25:07] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckfF46A.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-10-01 18:35:24] CKFinder.WARNING: ErrorException: unlink(C:\Users\Chau Minh Thien\AppData\Local\Temp\ckf68A6.tmp): Permission denied in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php:291 Stack trace: #0 [internal function]: CKSource\CKFinder\ExceptionHandler->errorHandler(2, 'unlink(C:\\Users...', 'F:\\Xampp\\htdocs...', 291, Array) #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Filesystem\File\UploadedFile.php(291): unlink('C:\\Users\\Chau M...') #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Command\FileUpload.php(169): CKSource\CKFinder\Filesystem\File\UploadedFile->__destruct() #3 [internal function]: CKSource\CKFinder\Command\FileUpload->execute(Object(Symfony\Component\HttpFoundation\Request), Object(CKSource\CKFinder\Filesystem\Folder\WorkingFolder), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(CKSource\CKFinder\Config), Object(CKSource\CKFinder\Cache\CacheManager), Object(CKSource\CKFinder\Thumbnail\ThumbnailRepository)) #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(139): call_user_func_array(Array, Array) #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\symfony\http-kernel\HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(575): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #9 {main} [] []
[2016-10-01 19:25:59] CKFinder.ERROR: CKSource\CKFinder\Exception\CKFinderException: CKFinder is disabled in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php:220 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #4 {main} [] []
[2016-10-01 19:41:24] CKFinder.WARNING: ErrorException: Use of undefined constant flase - assumed 'flase' in F:\Xampp\htdocs\DTMers\public\ckfinder\config.php:30 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\config.php(30): CKSource\CKFinder\ExceptionHandler->errorHandler(8, 'Use of undefine...', 'F:\\Xampp\\htdocs...', 30, Array) #1 [internal function]: CKSource\CKFinder\Config->{closure}() #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Authentication\CallableAuthentication.php(45): call_user_func(Object(Closure)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(218): CKSource\CKFinder\Authentication\CallableAuthentication->authenticate() #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #8 {main} [] []
[2016-10-01 19:41:25] CKFinder.WARNING: ErrorException: Use of undefined constant flase - assumed 'flase' in F:\Xampp\htdocs\DTMers\public\ckfinder\config.php:30 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\config.php(30): CKSource\CKFinder\ExceptionHandler->errorHandler(8, 'Use of undefine...', 'F:\\Xampp\\htdocs...', 30, Array) #1 [internal function]: CKSource\CKFinder\Config->{closure}() #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Authentication\CallableAuthentication.php(45): call_user_func(Object(Closure)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(218): CKSource\CKFinder\Authentication\CallableAuthentication->authenticate() #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #8 {main} [] []
[2016-10-01 19:41:25] CKFinder.WARNING: ErrorException: Use of undefined constant flase - assumed 'flase' in F:\Xampp\htdocs\DTMers\public\ckfinder\config.php:30 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\config.php(30): CKSource\CKFinder\ExceptionHandler->errorHandler(8, 'Use of undefine...', 'F:\\Xampp\\htdocs...', 30, Array) #1 [internal function]: CKSource\CKFinder\Config->{closure}() #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Authentication\CallableAuthentication.php(45): call_user_func(Object(Closure)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(218): CKSource\CKFinder\Authentication\CallableAuthentication->authenticate() #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #8 {main} [] []
[2016-10-01 19:41:25] CKFinder.WARNING: ErrorException: Use of undefined constant flase - assumed 'flase' in F:\Xampp\htdocs\DTMers\public\ckfinder\config.php:30 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\config.php(30): CKSource\CKFinder\ExceptionHandler->errorHandler(8, 'Use of undefine...', 'F:\\Xampp\\htdocs...', 30, Array) #1 [internal function]: CKSource\CKFinder\Config->{closure}() #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Authentication\CallableAuthentication.php(45): call_user_func(Object(Closure)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(218): CKSource\CKFinder\Authentication\CallableAuthentication->authenticate() #4 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #5 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #6 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #8 {main} [] []
[2016-10-01 19:42:16] CKFinder.ERROR: CKSource\CKFinder\Exception\CKFinderException: CKFinder is disabled in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php:220 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #4 {main} [] []
[2016-10-04 14:50:17] CKFinder.ERROR: CKSource\CKFinder\Exception\CKFinderException: CKFinder is disabled in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php:220 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #4 {main} [] []
[2016-10-06 16:40:58] CKFinder.ERROR: CKSource\CKFinder\Exception\CKFinderException: CKFinder is disabled in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php:220 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #4 {main} [] []
[2016-10-09 11:10:44] CKFinder.ERROR: CKSource\CKFinder\Exception\CKFinderException: CKFinder is disabled in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php:220 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #4 {main} [] []
[2016-10-09 11:10:55] CKFinder.ERROR: CKSource\CKFinder\Exception\CKFinderException: CKFinder is disabled in F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php:220 Stack trace: #0 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(506): CKSource\CKFinder\CKFinder->checkAuth() #1 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #2 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #3 F:\Xampp\htdocs\DTMers\public\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #4 {main} [] []
